### ISSUE TITLE
Supervisord is not started when running with docker compose

### ISSUE THREAD

**Issue by arnaudj** [atkinson/wagmi#8]
Currently, when starting wagmi with docker compose, it seems that supervisord is not started.

###  Possible cause
In `trading-server.yaml`, service "django", defines `command: ./wagmi/start.sh`
This overrides `DockerFile`'s `CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]"` [supervisord], as per https://github.com/compose-spec/compose-spec/blob/master/spec.md#command

### Current behavior
supervisord is not started (main effect: apscheduler is not started)

### Expect behavior - to confirm
to confirm: Do we want 
- `start.sh` to run only `python /app/manage.py runapscheduler`?
- `start.sh` to run [supervisord] as well?

More generally, we have different behaviors between:
supervisord.conf, start.sh, and manual steps in README.md (the readme mentions fixtures loading: exchanges.yaml, strategies.yaml)

suggestion: we should define what file is involved in which use case (eg: supervisord for prod? start.sh for local testing?)

**Comment by atkinson** [comment]
Beautifully written issue.  My thoughts:

1. Supervisord is in DockerFile only so we can run the worker (python /app/manage.py runapscheduler)
2. In local dev, we don't need the worker to run because we can run the strategies directly (e.g. ./manage.py rw_yolo).
3. You are correct, there should be just one way to run things... I don't have a strong view if we should use docker up or docker-compose.

Please suggest what you would like to do here.

thank you!

**Comment by arnaudj** [comment]
Thanks for the info. Agree with your points.

No strong opinion on my side, gave it some thoughts. At the time I wrote the question, I didn't notice the Makefile. It seems flexible enough.

So far I'm only seeing our docker-compose useful for CI, so tempted to limit it to that use case for now and close the issue.

For my info, could you share how you deploy to prod usually? `make test build runpg [createdb] run`? Using a non containerized DB? (would make sense).

Cheers
